services:
  database:
    image: mongo:latest
    container_name: db
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db

  # testdb:
  #   image: mongo:5.0
  #   container_name: mongodb_test_db
  #   ports:
  #     - 27018:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: user
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #     MONGO_INITDB_DATABASE: brotherhood-testdb

volumes:
  db_data:
    driver: local
